name: Deploy to AWS S3

on:
  push:
    branches:
      - master   # change to 'main' if your default branch is main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync files to S3 bucket
        uses: aws-actions/s3-sync@v2
        with:
          bucket: demo-ci-cd-bucket4321
          region: us-east-1
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
