name: Deploy Static HTML to AWS S3

on:
  push:
    branches:
      - master  # change to 'main' if your default branch is main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Sync files to S3
      - name: Sync files to S3
        uses: aws-actions/s3-sync@v1
        with:
          source: "./"                        # local repo root
          destination: "s3://demo-ci-cd-bucket4321"
          delete: true                        # remove files in bucket not in repo
